# Generated by Django 4.2.7 on 2023-12-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_family_schedule_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
