# Generated by Django 4.2.7 on 2023-11-25 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentor_id', models.AutoField(primary_key=True, serialize=False)),
                ('mentor_name', models.CharField(max_length=100)),
                ('professional_grade', models.CharField(max_length=100)),
                ('username', models.CharField(default=django.db.models.deletion.SET_NULL, max_length=20)),
                ('password', models.CharField(default=django.db.models.deletion.SET_NULL, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('reminder_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('child_id', models.AutoField(primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=40)),
                ('birth_date', models.DateField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.group')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('today_date', models.DateField()),
                ('is_arrived', models.BooleanField(default=False)),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.child')),
                ('mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.mentor')),
            ],
        ),
    ]
