# Generated by Django 4.2.7 on 2023-12-08 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_alter_attendance_today_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='mentor',
        ),
        migrations.AddField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentors.group'),
        ),
    ]
